### ISSUE TITLE
multisig : Wallet is inactive

### ISSUE THREAD

**Issue by kostrik2** [tonlabs/debots#16]
I have deployed and run the multisig debot. Then I have answered  0:5d3d540ebeb545be95ad05e22efc0ad3cb2e0172884fba2cedfde445ef16ebf9 to the question 'Which wallet do you want to work with?'. It is a demo wallet mentionned in this section https://github.com/tonlabs/debots#how-to-try-debot. This wallet opens in Surf.

The problem is that the debot answers "Wallet is inactive".

**Comment by joydark** [comment]
Please check that you deploy debot in net.ton.dev instead default 127.0.0.1 in [deploy debot script](https://github.com/tonlabs/debots/blob/main/multisig/deploy_debot.sh)

**Comment by kostrik2** [comment]
Thank you!
