### ISSUE TITLE
test wallet doesn't work (see https://github.com/tonlabs/debots#how-to-try-debot)

### ISSUE THREAD

**Issue by kostrik2** [tonlabs/debots#18]
`./tonos-cli account 0:5d3d540ebeb545be95ad05e22efc0ad3cb2e0172884fba2cedfde445ef16ebf9`
doens't work 
`Config: /home/anna/debots/helloworldModified/tonos-cli.conf.json`
`Input arguments:`
`address: 0:5d3d540ebeb545be95ad05e22efc0ad3cb2e0172884fba2cedfde445ef16ebf9`
`Connecting to https://net.ton.dev`
`Processing...`
`Succeeded.`
`Account not found.`

***
`./tonos-cli --url net.ton.dev debot fetch 0:09403116d2d04f3d86ab2de138b390f6ec1b0bc02363dbf006953946e807051e` doens't work 
`Cannot find smart contract with this address 0:09403116d2d04f3d86ab2de138b390f6ec1b0bc02363dbf006953946e807051e in blockchain`

**Comment by joydark** [comment]
Thank you for your report. Deployed  SafeMultisigWallet in net.ton.dev
